/* Generated by Together */

/**
 * For a description of Permanent visitors, follow hyperlink to the Administration use case
 * for issuing a new Permanent visitor permit.
 */
public class Permanent_visitor_permit extends Permit {
	
	public Permanent_visitor_permit(String permitHolder, Date currentDate) {
		super(permitHolder, currentDate);
		this.setPermitted(true);
		
	}
	
	/**
	 * The permanent permit newDayUpdate sets entered 
	 * to false and clears any vehicle references in 
	 * vehicleUsedToday.
	 */
	public void newDayUpdate() {
		this.setEntered(false);
		this.clearVehicleUsedToday();
	}
	
	/**
	 * The university permit newYearUpdate method 
	 * clears all Warnings and clears 
	 * all entries for the previous year
	 */
	public void newYearUpdate() {
		this.clearWarnings();
		this.clearEntries();
	}
}


