/* Generated by Together */

/**
 * For a description of University member permits, follow hyperlink to the
 * Administration use case for issuing a new University member permit.
 */
public class University_member_permit extends Permit {

    /**
     * The date that this permit was issued. This information is required in case a member
     * of the University leaves the University part way through the year and becomes eligible for a pro-rata rebate.
     * @label Issued on
     * @clientCardinality 1
     * @supplierCardinality 1
     * @link aggregation
     * @directed
     */
    private int lnkDateIssue;
    
  public University_member_permit(String permitHolder, Date currentDate) {
		super(permitHolder, currentDate);
			this.lnkDateIssue = currentDate.getDate();
			this.setPermitted(true);
    }


	/**
	 * Returns the day this university permit was issued
	 * 
	 * @return int		The day this permit was issued  
	 */
	public int getIssueDate() {
		return this.lnkDateIssue;
	}

	/**
	 * Sets the day this university permit was issued
	 * 
	 * @param int:date		The day this permit was issued  
	 */
	public void setIssueDate(int date) {
		this.lnkDateIssue = date;
	}

	/**
	 * The university permit newDayUpdate sets entered 
	 * to false, clears any vehicle references in 
	 * vehicleUsedToday and checks if the current 
	 * date is greater than or equal to the issue date
	 */
	public void newDayUpdate() {
		this.setEntered(false);
		this.clearVehicleUsedToday();
		if (currentDate.getDate() >= this.lnkDateIssue) 
		{
			this.setPermitted(true);
		} 
		else 
		{
			this.setPermitted(false);
		}
	}

	/**
	 * The university permit newYearUpdate method 
	 * sets the issue date to the first day of 
	 * the year, clears all Warnings and clears 
	 * all entries for the previous year
	 */
	public void newYearUpdate() {
		this.setIssueDate(1);
		this.clearWarnings();
		this.clearEntries();
	}
}
