/* Generated by Together */

/**
 * Each instance of Vehicle_info models an actual physical vehicle, so no two instances
 * may have the same registration number. There is no direct notation for this. Instead
 * the Vehicle list object collecting the Vehicles must enforce it by checking new additions
 * - the use of a HashTable in Vehicle_list with the registration number as key is helpful
 * with this.
 *
 * This class must contain at least the registration number, and may have any other attributes
 * that the University may from time to time find useful (such as car make, model, colour...).
 */
public class Vehicle_info {
    /**
     * The vehicle's registration number.
     */
    private String regNo;

    /**
     * Each vehicle (and so each registration number) is associated with exactly one permit,
     * which describes its authorization to enter the campus (or not!).
     *
     * This attribute references the permit associated with this vehicle. It alows the permit
     * status of any vehicle to be accessed via the Vehicle_list knowing only the registration
     * number - for example for barrier checks, recording warnings, and so on.
     *
     * Note that many vehicles may be associated with the same permit.
     * @supplierCardinality 1
     * @clientCardinality 1..*
     * @label Allowed entry by
     * @directed
     */
    private Permit lnkPermit;
    
    public Vehicle_info(String regNo, Permit permit) 
    {
    	this.lnkPermit = permit;
    	this.regNo = regNo;
    	
    	// This important line is what creates the two way relationship between a vehicles and their unique permit 
    	lnkPermit.setPermittedVehicle(regNo, this);
    }
    
	/**
	 * The getPermit method returns the reference to the unique permit 
	 * this vehicle is associated with.
	 * 
	 * @return Permit			The reference to the unique permit 
	 */
    public Permit getPermit() {
    	return lnkPermit;
    }
    
	/**
	 * The getRegNo method returns the String value of this Vehicle_info 
	 * objects registration which is also its key used to store it in 
	 * the list of vehicles.
	 *  
	 * @return String			The registration/key of this vehicle 
	 */
    public String getRegNo() {
    	return regNo;
    }
    
	/**
	 * The setRegNo method takes a String value and assigns it to 
	 * be this vehicles registration number.
	 *  
	 * @param String:regNo		The registration/key to be set 
	 */
    public void setRegNo(String regNo) {    	
    	this.regNo = regNo;
    }
    
	/**
	 * The setPermit method takes a permit and assigns it to 
	 * be this vehicles associated permit. Firstly it removes itself 
	 * from the current permits list of associated permits, it then 
	 * sets the new permit in place of the old one, and finally informs 
	 * that permit that this vehicle is now associated with it.
	 *  
	 * @param Permit:permit		The new permit to be set 
	 */
    public void setPermit(Permit permit) {    	
    	this.lnkPermit.removePermittedVehicle(getRegNo());
    	this.lnkPermit = permit;
    	permit.setPermittedVehicle(getRegNo(), this);
    }
}
